/* eslint-disable no-console */
import { useState, useEffect } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { RefreshCw, AlertCircle, CheckCircle2 } from "lucide-react";
import liff from "@line/liff";
import { liffApi } from "@/api/liff";

/**
 * LIFFUIDCapturePage — unauthenticated public page opened inside LINE via LIFF.
 *
 * Route: /liff/uid-capture
 * No BOLA login required.
 *
 * This is the UNIVERSAL LIFF page that handles two use cases:
 *
 * ── Use case A: Auto-Reply LIFF UID Capture ─────────────────────────────────
 *   Setup in LINE Developers Console:
 *     LIFF endpoint URL: https://<domain>/liff/uid-capture?line_oa_id=<oa-id>
 *   Params: liff_id, line_oa_id
 *   Flow: captures LINE UID → fires matching liff_uid_capture auto-reply rules
 *
 * ── Use case B: LON by Phone Greeting (PNP Track & Greet) ───────────────────
 *   Button URL generated by backend: https://liff.line.me/<liff_id>?liff_id=...&line_oa_id=...&token=...
 *   Params: liff_id, line_oa_id, token
 *   Flow: captures LINE UID → fires auto-reply rules → resolves PNP greeting token
 *         (links phone ↔ LINE UID in the backend, then redirects if redirect_url is returned)
 *
 * Full flow:
 *  1. Parse liff_id, line_oa_id, and optional token from URL / liff.state
 *  2. liff.init({ liffId })
 *  3. if !liff.isInClient() → show error
 *  4. if !liff.isLoggedIn() → liff.login()
 *  5. liff.getProfile() → { userId }
 *  6. POST /v1/public/liff/uid-captured { line_oa_id, line_user_id: userId }
 *  7. If token present: POST /v1/pnp/resolve-link-token { token, line_uid: userId }
 *     → if response has redirect_url, navigate there instead of closing
 *  8. liff.closeWindow()
 *
 * Send method for auto-reply: Push API (no reply token in LIFF context).
 * Dedup for auto-reply: controlled per rule via send_once setting.
 */

type PageStatus = "loading" | "error" | "success";

export function LIFFUIDCapturePage() {
  const [status, setStatus] = useState<PageStatus>("loading");
  const [errorMsg, setErrorMsg] = useState("");

  useEffect(() => { document.title = "Connecting with us…"; }, []);

  useEffect(() => {
    void initFlow();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function initFlow() {
    try {
      // LINE encodes original query params into liff.state before redirecting.
      // Parse liff_id, line_oa_id, and token from both current URL and liff.state.
      const urlParams = new URLSearchParams(window.location.search);
      let liffId = urlParams.get("liff_id") ?? "";
      let lineOAId = urlParams.get("line_oa_id") ?? "";
      let greetingToken = urlParams.get("token") ?? "";
      let redirectUrl = urlParams.get("redirect_url") ?? "";
      let appName = urlParams.get("app_name") ?? "";

      console.log("[LIFF] initFlow start url=", window.location.href);

      const liffState = urlParams.get("liff.state") ?? "";
      if (liffState) {
        try {
          // liff.state may contain a path prefix e.g. "/liff/uid-capture?foo=bar"
          // Strip everything up to and including the first "?" before parsing
          const decoded = decodeURIComponent(liffState);
          const qIdx = decoded.indexOf("?");
          const stateParams = new URLSearchParams(qIdx >= 0 ? decoded.slice(qIdx + 1) : decoded);
          if (!liffId) liffId = stateParams.get("liff_id") ?? "";
          if (!lineOAId) lineOAId = stateParams.get("line_oa_id") ?? "";
          if (!greetingToken) greetingToken = stateParams.get("token") ?? "";
          if (!redirectUrl) redirectUrl = stateParams.get("redirect_url") ?? "";
          if (!appName) appName = stateParams.get("app_name") ?? "";
          console.log("[LIFF] parsed liff.state → liffId=", liffId, "lineOAId=", lineOAId, "token=", greetingToken ? "yes" : "no");
        } catch {
          // ignore parse errors
        }
      }

      if (!liffId) {
        setErrorMsg("ไม่พบ LIFF ID กรุณาตรวจสอบการตั้งค่า");
        setStatus("error");
        return;
      }

      console.log("[LIFF] calling liff.init liffId=", liffId);
      await liff.init({ liffId });
      console.log("[LIFF] liff.init done, url now=", window.location.href);

      // Re-read ALL params after liff.init() — LINE SDK decodes liff.state into the URL at this point
      const params = new URLSearchParams(window.location.search);
      if (!lineOAId) lineOAId = params.get("line_oa_id") ?? "";
      if (!greetingToken) greetingToken = params.get("token") ?? "";
      if (!redirectUrl) redirectUrl = params.get("redirect_url") ?? "";
      if (!appName) appName = params.get("app_name") ?? "";

      console.log("[LIFF] after init: lineOAId=", lineOAId, "token=", greetingToken ? "yes" : "no", "redirectUrl=", redirectUrl);

      if (!lineOAId) {
        setErrorMsg("ไม่พบ LINE OA ID กรุณาตรวจสอบการตั้งค่า");
        setStatus("error");
        return;
      }

      if (!liff.isInClient()) {
        setErrorMsg("กรุณาเปิดลิงก์นี้ผ่าน LINE เท่านั้น");
        setStatus("error");
        return;
      }

      if (!liff.isLoggedIn()) {
        console.log("[LIFF] not logged in → calling liff.login()");
        liff.login({ redirectUri: window.location.href });
        return;
      }

      const profile = await liff.getProfile();
      console.log("[LIFF] got profile userId=", profile.userId);

      // Step 1: Capture LINE UID → fires liff_uid_capture auto-reply rules
      console.log("[LIFF] calling uidCaptured lineOAId=", lineOAId);
      await liffApi.uidCaptured(lineOAId, profile.userId);
      console.log("[LIFF] uidCaptured done");

      // Step 2 (optional): Resolve PNP greeting token → links phone ↔ LINE UID.
      // Must be awaited before redirecting — a fire-and-forget fetch gets cancelled
      // the instant window.location.href changes (especially in LINE WebView).
      if (greetingToken) {
        console.log("[LIFF] calling resolveGreetingToken");
        try {
          await liffApi.resolveGreetingToken(greetingToken, profile.userId);
          console.log("[LIFF] resolveGreetingToken done");
        } catch (err) {
          console.warn("[LIFFUIDCapture] resolveGreetingToken error (non-fatal):", err);
          // non-fatal: continue to redirect even if linking failed
        }
      }

      // Step 3: Redirect URL takes priority over closing LIFF
      // The redirect URL is embedded in the LIFF link by the backend at send time,
      // with template variables already substituted — no extra backend call needed.
      if (redirectUrl) {
        console.log("[LIFF] redirecting to", redirectUrl);
        window.location.href = redirectUrl;
        return;
      }

      setStatus("success");

      // Close the LIFF window after a short delay so the user sees the success state
      setTimeout(() => {
        try {
          liff.closeWindow();
        } catch {
          // closeWindow may fail outside full LIFF context — stay on success screen
        }
      }, 1500);
    } catch (err) {
      console.error("[LIFFUIDCapture] error:", err);
      setErrorMsg(err instanceof Error ? err.message : "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง");
      setStatus("error");
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <Card className="w-full max-w-sm shadow-md">
        <CardContent className="pt-8 pb-8 flex flex-col items-center gap-4 text-center">
          {status === "loading" && (
            <>
              <RefreshCw size={40} className="text-line animate-spin" />
              <p className="text-sm text-muted-foreground">กำลังดำเนินการ...</p>
            </>
          )}

          {status === "success" && (
            <>
              <CheckCircle2 size={40} className="text-green-500" />
              <p className="text-base font-medium text-gray-800">เรียบร้อยแล้ว</p>
              <p className="text-sm text-muted-foreground">หน้าต่างนี้จะปิดโดยอัตโนมัติ</p>
            </>
          )}

          {status === "error" && (
            <>
              <AlertCircle size={40} className="text-destructive" />
              <p className="text-base font-medium text-gray-800">เกิดข้อผิดพลาด</p>
              <p className="text-sm text-muted-foreground">{errorMsg}</p>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
